### ISSUE TITLE
sofa report error

### ISSUE THREAD

**Issue by wei-yuan** [cyliustack/sofa#17]
Hi, dear @cyliustack 

### Basic info
sofa: latest version
OS: Ubuntu 16.04

### Problem statement
I execute the example in readme file with the following instruction:
   
    sofa record "python tf_cnn_benchmarks.py --num_gpus=8 --batch_size=64 --model=resnet50 -- variable_update=parameter_server --num_warmup_batches=1 --num_batches=3" 

then I 

    sofa report

But sadly, it failed and I got error message without showing graphical results on my web browser

### Error meassge
> Traceback (most recent call last):
  File "/home/paslab/wei-yuan/sofa/sofa/bin/sofa", line 173, in <module>
    sofa_analyze(logdir, cfg)
  File "/home/paslab/wei-yuan/sofa/sofa/bin/sofa_analyze.py", line 360, in sofa_analyze
    with open("/tmp/sofa_hints/xring_order.txt", "w") as f:
PermissionError: [Errno 13] Permission denied: '/tmp/sofa_hints/xring_order.txt'

Can you give me some hint here please? 

Thanks

ps. Good work!

**Comment by cyliustack** [comment]
Sofa try to create a file at /tmp/sofa_hints/,  but it encountered a permission issue; I will try to fix it.
