### ISSUE TITLE
quit() should not be used in programs

### ISSUE THREAD

**Issue by pjw91** [cyliustack/sofa#26]
According to the [document](https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module), 
> The site module (which is imported automatically during startup, except if the -S command-line option is given) adds several constants to the built-in namespace. They are useful for the interactive interpreter shell and should not be used in programs.
please use `sys.exit()` instead.

For the successful execution, use `sys.exit()`; otherwise, use `sys.exit(1)`.

**Comment by cyliustack** [comment]
Thanks,  @pjw91 ! I will fix it soon.
