### ISSUE TITLE
pkill may kill others' processes

### ISSUE THREAD

**Issue by pjw91** [cyliustack/sofa#6]
https://github.com/cyliustack/sofa/blob/83d1a378a03524b3a507c5e197d1965ba5ddf33b/bin/sofa_record.py#L82-L85

When someone who shares the same account runs sofa as well, we also kill his processes.

**Comment by cyliustack** [comment]
Sure. the killing actions are now handled by subprocess.terminate().

Also, those killing actions inside exception handling will be replaced by the terminate() as soon as possible.
