### ISSUE TITLE
ModuleNotFoundError: No module named 'dummy_plugin'

### ISSUE THREAD

**Issue by Lzhang-hub** [cyliustack/sofa#64]
I have install sofa successfully!
`./tools/prepare.sh`

![image](https://user-images.githubusercontent.com/57925599/138249023-7489c087-aa8e-44f8-928d-0a11a9ad32f9.png)
`./install.sh /zl/place`

![image](https://user-images.githubusercontent.com/57925599/138249152-d50321ef-e6b2-49d1-9f16-3ec31c9135c5.png)

But,when I use `sofa record`,get the error as follow,can you give me some advice.Thanks!

###########
Traceback (most recent call last):
  File "/zl/place/sofa/bin/sofa", line 21, in <module>
    import dummy_plugin
ModuleNotFoundError: No module named 'dummy_plugin'

**Comment by Lzhang-hub** [comment]
Does it depend on the Python version? I use python3.8

**Comment by cyliustack** [comment]
Thanks for your report. let me check.

**Comment by cyliustack** [comment]
> Does it depend on the Python version? I use python3.8

[Lzhang-hub](https://github.com/Lzhang-hub) Thanks for your report. let me check.

**Comment by cyliustack** [comment]
> Does it depend on the Python version? I use python3.8

I think you missed the activation of SOFA environment. 

So, please do `source /zl/place/sofa/tools/activate.sh` before running sofa.

Let me know if you still encounter any problems with running sofa.
